### ISSUE TITLE
编译有问题，没发现库里有相关的CPP文件

### ISSUE THREAD

**Issue by binzhiyuan** [react-native-oh-library/picker#8]
根据接入文档，CMakeLists中需要链接该库来编译，单实际库里没有相关的文件，cpp目录也不存在

**Comment by xiaolieask** [comment]
根据文档：https://gitee.com/react-native-oh-library/docs/blob/master/zh-cn/fabric.md#harmonyosarkts-fabric-%E5%92%8C-capi-fabric-%E5%85%B1%E6%9C%89%E9%83%A8%E5%88%86中的ArkTS Fabric部分接入

**Comment by xiaolieask** [comment]
根据文档：https://gitee.com/react-native-oh-library/docs/blob/master/zh-cn/fabric.md#harmonyosarkts-fabric-%E5%92%8C-capi-fabric-%E5%85%B1%E6%9C%89%E9%83%A8%E5%88%86   中的ArkTS Fabric部分接入

**Comment by xiaolieask** [comment]
> 根据接入文档，CMakeLists中需要链接该库来编译，单实际库里没有相关的文件，cpp目录也不存在
参考文档：https://gitee.com/react-native-oh-library/docs/blob/master/zh-cn/fabric.md#harmonyosarkts-fabric-%E5%92%8C-capi-fabric-%E5%85%B1%E6%9C%89%E9%83%A8%E5%88%86   ArkTS Fabric部分
